# Generated by Django 2.1.3 on 2018-12-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181215_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Substask',
            new_name='Subtask',
        ),
    ]
