# Generated by Django 2.1.3 on 2018-12-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20181215_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtaskId',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='taskId',
            new_name='parent',
        ),
    ]
