# Generated by Django 2.1.3 on 2018-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20181215_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='children',
            field=models.ManyToManyField(related_name='_post_children_+', to='tasks.Post'),
        ),
    ]
