# Generated by Django 2.1.3 on 2018-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='children',
            field=models.ManyToManyField(to='tasks.Post'),
        ),
    ]
