# Generated by Django 2.1.3 on 2018-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20181217_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='complete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='optional',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
