# Generated by Django 2.1.3 on 2018-12-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20181218_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='complete_date',
            field=models.DateField(null=True),
        ),
    ]
