# Generated by Django 2.1.3 on 2018-12-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_post_complete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='complete_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='complete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='optional',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
