# Generated by Django 2.1.4 on 2018-12-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20181220_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='completable',
            field=models.BooleanField(default=True),
        ),
    ]
